// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "Bengaluru",
  "venue": "M Chinnaswamy Stadium",
  "capacity": 15,
  "eventTitle": "VIP Connect — Bengaluru Leadership Dinner",
  "heroImageUrl": "/venue/long-table.png",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "Bengaluru Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Fifteen leaders.\\nPlatinum lounge overlooking the pitch.\\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other’s assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What’s working, what’s not, and what the next twelve months look like.",
    "M Chinnaswamy Stadium's platinum lounge combines the thrill of live cricket with sophisticated hospitality."
  ],
  "agendaItems": [
    {
      "time": "6:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "6:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "6:45 PM",
      "title": "Dinner",
      "description": "An evening of gourmet cuisine and curated cocktails as one of the season's premier cricket matches unfolds before us."
    },
    {
      "time": "9:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "6:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "6:30 PM",
      "label": "Executive session"
    },
    {
      "time": "6:45 PM",
      "label": "Dinner"
    },
    {
      "time": "9:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 15 people. Small enough that everyone speaks, diverse enough that you’ll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you’d wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "M Chinnaswamy Stadium accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they’ll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — Bengaluru Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-bengaluru.vercel.app",
  "slug": "moloco-event-bengaluru",
  "eventSubtitle": "Cricket, cocktails, and commerce conversations in Bengaluru's iconic stadium",
  "venueAddress": "M Chinnaswamy Stadium, Cubbon Park, Bengaluru 560001",
  "venueAddressFull": "M Chinnaswamy Stadium, Cubbon Park, Bengaluru 560001, India",
  "date": "April 24, 2024",
  "dateFull": "Wednesday, April 24",
  "dateISO": "2024-04-24",
  "calendarDateStart": "20240424T180000",
  "calendarDateEnd": "20240424T210000",
  "time": "6:00 PM",
  "timezone": "Asia/Kolkata",
  "timezoneAbbr": "IST",
  "venueDescription": "The M Chinnaswamy Stadium stands as one of cricket's premier venues, home to Royal Challengers Bengaluru and witness to countless legendary matches. Our exclusive platinum lounge offers panoramic views of the pitch with floor-to-ceiling windows, combining the electric atmosphere of live cricket with refined hospitality. The space features premium furnishings and elevated sightlines that place guests at the heart of the action.",
  "venueCapacityNote": "The platinum lounge provides an intimate setting for fifteen executives with unobstructed stadium views.",
  "venueDiningNote": "Gourmet Indian and international cuisine paired with expertly crafted cocktails and premium spirits.",
  "venueDirections": "Located in Cubbon Park, the stadium is accessible via Cubbon Park Metro Station (Purple Line). Enter through the VIP entrance on Kasturba Road, where our team will escort you to the platinum lounge. Valet parking is available for those arriving by car.",
  "venueExperienceLine": "M Chinnaswamy Stadium's platinum lounge combines the thrill of live cricket with sophisticated hospitality.",
  "dinnerDescription": "An evening of gourmet cuisine and curated cocktails as one of the season's premier cricket matches unfolds before us.",
  "mapsUrl": "https://maps.google.com/maps?q=M+Chinnaswamy+Stadium,+Cubbon+Park,+Bengaluru"
};
